### ISSUE TITLE
AS2 server is not multithreaded

### ISSUE THREAD

**Issue by avnerw1** [phax/as2-lib#108]
Hi (again) Phillip,

We noticed the as2 server cannot accept more than one connection concurrently. Is that correct?
If I want to send multiple AS2 messages at the same time, is it possible?

Thanks,
Avner

**Comment by phax** [comment]
Hi, that is very likely possible. I took this over when I forked the project but never out effort into it. I  suggest you go for the "Servlet based" solution so that you can use a regular application server like Tomcat, Jetty or so. They are multithreaded and offer all the configuration possibilities you most likely need :)
