### ISSUE TITLE
AS2 server error when decrypting message "Certificate does not match part signature"

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#114]
Hi Philip,
When decrypting message that sent from as2-lib client to our as2-server ( also as2-lib) we are getting the following error:
Certificate does not match part signature
This code is arrived from BCCryptoHelper::decrypt method ( line 439 in 4.5.5 version)
 if (aRecipient == null)
      throw new GeneralSecurityException ("Certificate does not match part signature");
Do you know what is the root cause for this issue and how to solve those meesages?
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi Philip,
Do you have an idea what is the issue here and how to solve this?
Thanks,
Itay

**Comment by phax** [comment]
I am not sure.
There is a log message exactly before that "if": `Error retrieving RecipientInformation` - is that contained in your log file?
Is it possible that the sending party uses and outdated certificate compared to what the receiver expects? Some kind of a certificate mismatch is the best I can come up with.

**Comment by ihudedi** [comment]
Hi Philip,
Looks like mismatch of AS2 ID and alias
Thanks a lot,
Itay

**Comment by asdfghjklzxcvbnmmmmmmmm** [comment]
> Hi ihudedi, 
I had the same problem，But my AS2 ID and alias Settings are the same
When decrypting message that sent from as2-lib client to our as2-server ( also as2-lib) we are getting the following error:
Certificate does not match part signature
This code is arrived from BCCryptoHelper::decrypt method ( line 439 in 4.5.5 version)
if (aRecipient == null)
throw new GeneralSecurityException ("Certificate does not match part signature");
Do you know what is the root cause for this issue and how to solve those meesages?
Thanks,
Itay

**Comment by phax** [comment]
@asdfghjklzxcvbnmmmmmmmm 
Depending on the keystore format you are using (JKS or PKCS12) the alias name is case-sensitive or not. So please make sure the names are completely correct and have neither leading nor trailing whitespaces.
