### ISSUE TITLE
Warnings when checking out

### ISSUE THREAD

**Issue by Enryuu2** [phax/as2-lib#22]
Hello helger first of all i would like to thank you for the great work your doing. and i might use your work in the near future and create GUI to work with server.

When checking out out a project it comes with 80 or so warnings, 

1st warning is about adding a serialize id to the classes. could you please add automatic generated id's? right now i have to add it myself with every revision update.

second is about dead code. maby add suppression warnings?

third warning: XML files changelog and findbugs-exlusion. could oyu add <!DOCTYPE XML> to it to suppress no grammer contrainst warnings

kind regards,

**Comment by phax** [comment]
Hi! Call me Philip.... :)
Concerning the warnings: I assume you are using Eclipse (as I also do). I disabled these warnings because they don't fit me.

Concerning the serialization ID: they are automatically generated by the runtime based on the class layout if they are not specified. For this is the better approach because I tend to forget changing the IDs when I change something in the class :) See the first answer at http://stackoverflow.com/questions/285793/what-is-a-serialversionuid-and-why-should-i-use-it for technical details.

Concerning the dead code: i prefer to have some "if (false)" in my code, because that means that any changes done by refactoring are also handled in these "dead" blocks.

And concerning the "DOCTYPE" things: as these are plain XML files, they don't need a DOCTYPE (see the XML spec) as there is no DTD available.

I think it is best if you simply disable theses warnings in Eclipse :)

If you do a GUI, I'd be happy to link it from the project page - and you surely saw the basic https://github.com/phax/as2-server project - that may be a starting point.

// Philip

**Comment by Enryuu2** [comment]
okey. thank you for your time.

**Comment by phax** [comment]
If you need help how to disable the settings in Eclipse, just let me know.
