### ISSUE TITLE
After upgrading to as2-lib 4.2.0, receiving multiple ACK2s

### ISSUE THREAD

**Issue by sheebaveeva** [phax/as2-lib#84]
After upgrading to as2-lib 4.2.0, I am receiving many ACK2, one in every 5 minutes or so for 1 hour span of time, since receiving the first ACK2. Is there is anything internally causing this ACK2 to be sent by the other center. I don't remember seeing this issue with the previous version 3.1.0. Any help would be greatly appreciated.

**Comment by phax** [comment]
Hi, sorry to inform you, that I have no idea what you mean with "ACK2" - is it a TCP thingy?
Are you using the new "large file" support?

**Comment by sheebaveeva** [comment]
Sorry for not being very clear. 
When B sends data  to A, MDN created by A with the AS2 library, is failing at B in validating the Signature. (error showing at B : "The receipt signature could not be verified: No more data.") So this one is triggering the B to send the data over and over to A. 
Wondering if there is a way to verify if the MDN is created with the correct key?

**Comment by phax** [comment]
That heavily depends on your setup.
Do you have "point to point" relationships, where A and B exchanged X509 certificates? Both sides must have added the other side's certificate into their truststore. Please ensure, that the alias of the X509 certificate in the truststore is handled case sensitive ('a' != 'A').
All you can basically do is to increase logging, so that you can trace what certifcate "A" uses to sign the MDN

**Comment by phax** [comment]
@sheebaveeva Any news on this? Did you try version 4.3.0?

**Comment by phax** [comment]
@sheebaveeva please re-open if you have news
